apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-deployment
  labels:
    app: seller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller
  template:
    metadata:
      labels:
        app: seller 
    spec:
      containers:
      - name: seller
        image: nowen321/seller:latest
        ports:
        - containerPort: 8084
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: seller-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 8084
    nodePort: 31112
