apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user 
    spec:
      containers:
      - name: nodeserver
        image: nowen321/user:latest
        ports:
        - containerPort: 8081
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 8081
    nodePort: 311102
