apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products 
    spec:
      containers:
      - name: products
        image: nowen321/products:latest
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: products 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
    nodePort: 31113
